### ISSUE TITLE
Option to allow blog posts on all categories?

### ISSUE THREAD

**Issue by ted-strauss-K1** [scossar/discourse-blog-post#4]
I would like to allow posts from any category to be blog posts.
Is there a way to do that without listing all the categories in the settings field?

**Comment by scossar** [comment]
No, not without making some changes to the code.

I'm not supporting this plugin anymore, the Discourse code changes too quickly for me to be able to support it without doing a fair amount of work. I think using the WP Discourse plugin is a better alternative for combining styled posts with Discourse comments. It's being actively developed (by me) and there's lots of support for people using it. If the blog-post plugin is important to your forum, you should try to find someone who would like to take it over.

**Comment by ted-strauss-K1** [comment]
ok no problem.
I quite like the simplicity of this plugin, and its ability to improve the look of a post.
So i'll keep using it for now
